#!/bin/sh
#
# Copyright (c) 2015 Fehmi Noyan ISI. All rights reserved.
# See the LICENSE for usage information
#
# Simple shell script to adjust laptop LCD backlight in FreeBSD
# Script uses hw.acpi.toshiba sysctl tunable to change the LCD backlight
# requires x11/xdialog port to be installed

# Get the initial value
lcd_initial=`sysctl hw.acpi.toshiba.lcd_brightness | awk '{print $2}'`

# Set a new value
exec 3>&1
lcd_b=`Xdialog --title "Brigtness" --rangebox "Adjust LCD Backlight" 0 0 1 7 $lcd_initial 2>&1 1>&3`
exec 3>&-

sysctl hw.acpi.toshiba.lcd_brightness=$lcd_b